name = "Perpendicular"
author = "Diamondback88"
version = "Alpha 1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6fe0f9de5b052873b6b652462f88a27c63a714908242d82b314e3dffd31489c0"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
