
[renderers]

	[renderers.inventory_renderer]
		#Effect renderer to be used.
		#This setting might not be respected when not enough screen space is available. To force this setting disable "allow_fallback".
		#Allowed Values: NONE, GUI_SMALL, GUI_COMPACT, INVENTORY_COMPACT, INVENTORY_FULL_SIZE
		renderer_type = "INVENTORY_FULL_SIZE"

	[renderers.gui_renderer]
		#Prevent status effects with infinite duration from showing.
		hide_infinite_effects = false
		#Allow effect renderer to fall back to a more compact version (when available) if not enough screen space exists. Otherwise effect widgets might run off-screen.
		allow_fallback = true
		#Screen side to render status effects on.
		#Allowed Values: LEFT, RIGHT
		screen_side = "LEFT"
